services:
  printy:
    build: .
    container_name: printy-app
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
      - ./cups_config:/etc/cups
    restart: unless-stopped
    # Jeśli wymagane jest specyficzne logowanie:
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
