services:
  printy:
    build: .
    container_name: printy-app
    ports:
      - "3030:3030"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
    # Jeśli wymagane jest specyficzne logowanie:
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"
